server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]': # Patrón de ruta global
            allowedOrigins:
              - http://localhost:5173
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: ms-1
          uri: lb://ms-1
          predicates:
            - Path=/api/v1/simulacion/**
        - id: ms-2
          uri: lb://ms-2
          predicates:
            - Path=/api/v1/usuario/**
        - id: ms-3
          uri: lb://ms-3
          predicates:
            - Path=/api/v1/solicitud/**
        - id: ms-4
          uri: lb://ms-4
          predicates:
            - Path=/api/v1/evaluacion/**
        - id: ms-5
          uri: lb://ms-5
          predicates:
            - Path=/api/v1/seguimiento/**